displayName=Spell Timers
author=DapperMickie
description=Timers for skilling spells with delayed or batched results
tags=magic,skilling,timer,lunar,arceuus,normal,spell,spellbook,humidify,superglass,make,degrime,spin,flax,tan,leather,plank,string,jewellery,bake,pie
version=
plugins=github.com.dappermickie.spelltimers.SpellTimerPlugin
build=standard
